services:
  web:
    depends_on:
      - postgres_db
    build: 
      context: ./test_setup
      dockerfile: Dockerfile
    image: test_k8s:v1
    env_file:
      - ./test_setup/.env
    ports:
      - "8001:8000"
    command: sh -c "/app/migrate.sh && /app/entrypoint.sh"

  postgres_db:
    image: postgres
    expose: 
      - 5432
    ports:
      - "5433:5432"
    env_file:
      - ./test_setup/.env
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U root"]
      interval: 2s
      retries: 10
      timeout: 2s

volumes:
  db_data:
